### ISSUE TITLE
Encryption Issue

### ISSUE THREAD

**Issue by swagkarna** [Technowlogy-Pushpender/crypter#1]
Could not encrypt some python scripts

**Comment by Technowlogy-Pushpender** [comment]
Can you provide the python script which are unable to encrypt, so that i can test, or what error you are facing.

**Comment by swagkarna** [comment]
This python file cannot  not be encrypted check this
[Check this.zip](https://github.com/Technowlogy-Pushpender/crypter/files/4533156/Check.this.zip)

**Comment by Technowlogy-Pushpender** [comment]
Check it now

**Comment by swagkarna** [comment]
Its working fine thanks
