### ISSUE TITLE
Base64 Encryption?

### ISSUE THREAD

**Issue by kotval** [Technowlogy-Pushpender/crypter#2]
You should change the name of the function for Base64. There is a reason you used the python function called encode, not encrypt. Base64 is not encryption, simply encoding.

**Comment by Technowlogy-Pushpender** [comment]
I know that, I initially coded the AES module then i just make clone of AES
module and edited it make new module for base64

Name hardly matter, Will change it whenever i update it with new feature

**Comment by Technowlogy-Pushpender** [comment]
Renamed the Module
