### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x90 

### ISSUE THREAD

**Issue by r3dt3am** [Technowlogy-Pushpender/crypter#3]
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x90 in position 2: invalid start byte

I get the above error, when ever I try and sue the crypter. The .bak file is created but then the program fails.

Trace is as follows

[?] Want to BypassVM (y/n): y

[*] Making Backup ...
[+] Done !

[*] Initaiting Base64 Encryption Process ...
Traceback (most recent call last):
  File "Crypter.py", line 28, in <module>
    test2.encrypt(path)
  File "/home/merlin/work/crypter/Base64_encrypt.py", line 11, in encrypt
    lines_list = f.readlines()
  File "/usr/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x90 in position 2: invalid start byte

**Comment by Technowlogy-Pushpender** [comment]
I Have Updated The Source Codes
Check It Now Again!

**Comment by r3dt3am** [comment]
Yupp its working now. thanks for the gr8 share
